### ISSUE TITLE
Plugin manager not opening

### ISSUE THREAD

**Issue by wduda** [JuneStepp/OneLauncher#36]
Hi,

the plugin manager window has stopped opening for me on one machine. Using OneLauncher for LOTRO. An error message opos up in the log:

`2021-12-07 11:01:37,971 - MainWindow - CRITICAL - 776 - Uncaught exception:
Traceback (most recent call last):
  File "D:\a\OneLauncher\OneLauncher\OneLauncher\MainWindow.py", line 353, in btnAddonManagerSelected
  File "D:\a\OneLauncher\OneLauncher\OneLauncher\AddonManager.py", line 241, in __init__
  File "D:\a\OneLauncher\OneLauncher\OneLauncher\AddonManager.py", line 394, in getInstalledPlugins
  File "D:\a\OneLauncher\OneLauncher\OneLauncher\AddonManager.py", line 402, in removeManagedPluginsFromList
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\onelauncher-YyRzEafU-py3.9\lib\site-packages\defusedxml\minidom.py", line 22, in parse
  File "C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs\onelauncher-YyRzEafU-py3.9\lib\site-packages\defusedxml\expatbuilder.py", line 86, in parse
  File "c:\hostedtoolcache\windows\python\3.9.6\x64\lib\xml\dom\expatbuilder.py", line 207, in parseFile
xml.parsers.expat.ExpatError: mismatched tag: line 13, column 2`

**Comment by JuneStepp** [comment]
Can you email your full log file to `git@junestepp.me`?

**Comment by wduda** [comment]
I can do that only next week once I have access to that machine again and pull the backup of the log.

I can however say with confidence that once moved the log, OneLauncher created a new log file and what I posted was the only content.

**Comment by JuneStepp** [comment]
Would it be possible for you to instead send the plugins folder, then?

**Comment by wduda** [comment]
I missed that comment and have lost access to the machine where this was happening as well. Not sure what to do now; from my side this is closed since the issue no longer affects me and I have lost any means to reproduce it.

**Comment by JuneStepp** [comment]
Seems like it was a specific plugin with a messed up compendium file. I'll add handling for situations like that.
