### ISSUE TITLE
Linux: Cannot Open Shared Object File

### ISSUE THREAD

**Issue by FibroJedi** [JuneStepp/OneLauncher#43]
Hey,

So I tried the Linux-only installer of this (I'm intrigued by an alternative launcher) and have the following error:

`Error running /home/user/Games/OneLauncher/build/OneLauncher : Traceback (most recent call last):
 File "/home/name/Projects/OneLauncher/OneLauncher/.venv/lib/python3.9/site-packages/cx_Freeze/initscripts/__startup__.py", line 74, in run
  File "/home/name/Projects/OneLauncher/OneLauncher/.venv/lib/python3.9/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
  File "RunOneLauncher", line 30, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/name/Projects/OneLauncher/OneLauncher/OneLauncher/Runner.py", line 29, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/name/Projects/OneLauncher/OneLauncher/OneLauncher/MainWindow.py", line 37, in <module>
  File "/tmp/embedded.8xarykpp.zip/shibokensupport/feature.py", line 140, in _import
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/lib/python3.9/ssl.py", line 98, in <module>
  File "/tmp/embedded.8xarykpp.zip/shibokensupport/feature.py", line 140, in _import
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
The application will exit now.`

But given /home/name/ doesn't exist on my system...might that be the issue?

I'll try the Windows one through Lutris (my usual platform where LOTRO is installed anyhow).

**Comment by JuneStepp** [comment]
Heylo! Thanks for sending this in!

The project does work through Wine, but given that you use Linux and have some technical experience, I'd recommend [running from source ](https://github.com/JuneStepp/OneLauncher#development-install). I've been focussing on 2.0 for almost two years now, so doing a new 1.x build wouldn't be completely trivial.  (Last hotfix was literally done with a hex editor) Current 2.0 is pretty solid on Linux and much better than the old version, though. I just haven't released builds yet, since quite a few major changes are still on the way.

Will try to get something fixing this out as business allows here in the near future.

**Comment by FibroJedi** [comment]
> @FibroJedi I know this is old, but I'd make sure openssl is installed via your package manager.
> 
> Additionally, I ran into this error on arch: `error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`
> 
> which was resolved with a `sudo pacman -Syu libxcrypt-compat` - in case anyone else run's into this.

I haven't had time to reattempt this in any form recently, it's been a weird few months. It would surprise me not to have OpenSSL given what I use my machine for, but there's certainly no harm in having it installed.

I don't know if it's worth trying to get a V1 working, if a much better V2 is in the works and my current launcher does work fine, albeit with a few hiccups now and then!

**Comment by gtbX** [comment]
@FibroJedi It's likely that your system has OpenSSL 3.0 installed, while OneLauncher requires 1.1.

Many distros have switched over to 3.0 at this point, but provide a openssl "-compat" package for software that relies on 1.1. In my case (Gentoo) it's called "openssl-compat" - you'll have to look through your distro's packages for the appropriate one.

**Comment by JuneStepp** [comment]
A pre-release of 2.0 is now out that should resolve these issues.

https://github.com/JuneStepp/OneLauncher/releases/tag/v2.0.rc1
