### ISSUE TITLE
Occassional error on launch fetching news feed

### ISSUE THREAD

**Issue by Git-Forked** [JuneStepp/OneLauncher#60]
```
main_window - ERROR - Network error while downloading newsfeed
main_window - ERROR - Network error while downloading newsfeed
Traceback (most recent call last):
  File "/tmp/onefile_192960_1721903384_439227/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
  File "/tmp/onefile_192960_1721903384_439227/httpx/_transports/default.py", line 373, in handle_async_request
  File "/tmp/onefile_192960_1721903384_439227/httpcore/_async/connection_pool.py", line 216, in handle_async_request
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/onefile_192960_1721903384_439227/onelauncher/main_window.py", line 913, in load_newsfeed
  File "/tmp/onefile_192960_1721903384_439227/onelauncher/network/game_newsfeed.py", line 21, in newsfeed_url_to_html
  File "/tmp/onefile_192960_1721903384_439227/httpx/_client.py", line 1801, in get
  File "/tmp/onefile_192960_1721903384_439227/httpx/_client.py", line 1574, in request
  File "/tmp/onefile_192960_1721903384_439227/httpx/_client.py", line 1661, in send
  File "/tmp/onefile_192960_1721903384_439227/httpx/_client.py", line 1689, in _send_handling_auth
  File "/tmp/onefile_192960_1721903384_439227/httpx/_client.py", line 1726, in _send_handling_redirects
  File "/tmp/onefile_192960_1721903384_439227/httpx/_client.py", line 1763, in _send_single_request
  File "/tmp/onefile_192960_1721903384_439227/httpx/_transports/default.py", line 372, in handle_async_request
  File "/tmp/onefile_192960_1721903384_439227/contextlib.py", line 158, in __exit__
  File "/tmp/onefile_192960_1721903384_439227/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
httpx.ReadTimeout
```

**Comment by JuneStepp** [comment]
Retrying the network connections is already up for the next release. Might increase the timeout a bit too.
